//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 YYSAssist.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDI_ICON_LOGO                   99
#define IDS_ABOUTBOX                    101
#define IDD_YYS_MAIN_DLG                102
#define IDD_DIALOG_GAME                 129
#define IDD_YUHUN_DLG                   131
#define IDD_JueXing_DLG                 134
#define IDD_RiLunZhiYun_DLG             136
#define IDD_YongShengZhiHai_DLG         138
#define IDD_TanSuo_DLG                  141
#define IDD_YaoQiFengYin_DLG            145
#define IDD_YeYuanHuo_DLG               147
#define IDD_YuLing_DLG                  149
#define IDD_GeRenTuPo_DLG               151
#define IDD_NEW_EVENT_DLG               153
#define IDD_Rest_DLG                    155
#define IDD_INDEPENDENT                 156
#define IDD_RunLog                      158
#define IDD_CHANGEEQUIP                 160
#define IDI_ICON_FIRST                  161
#define IDI_ICON_ML                     163
#define IDD_TIMER                       164
#define IDI_ACTIVE                      165
#define IDD_TIPS                        168
#define IDC_BTN_DELETE_SELECT_TASK      169
#define IDD_GLOBAL                      169
#define IDC_BTN_CLEAR_TASK_LIST         170
#define IDD_SUPERKING                   170
#define IDD_FIXTEAMER                   171
#define IDD_PUSHPLUS                    172
#define IDC_WINDOW_TYPE                 999
#define IDC_TAB_MIAN                    1000
#define IDC_TAB_MODE                    1001
#define IDC_YH_ROUND                    1002
#define IDC_COMBO_YH_PREFER_FRIENG      1003
#define IDC_COMBO_W_OR_H                1005
#define IDC_COMBO_RLZY_AUTO_BONUS       1006
#define IDC_COMBO_YH_LAYER              1009
#define IDC_COMBO_YH_AUTO_BONUS         1012
#define IDC_COMBO_YSZH_AUTO_BONUS       1014
#define IDC_CHECK_YH_VICTORY            1019
#define IDC_BTN_YH_ADDTOLIST            1034
#define IDC_HANDLE_TIPS2                1044
#define IDC_DRAG_HANDLE                 1051
#define IDC_GET_HD                      1055
#define IDC_GET_HD_TEXT                 1056
#define IDC_HANDLE_TIPS1                1058
#define IDC_JX_ROUND                    1061
#define IDC_COMBO_JX_MODE               1063
#define IDC_COMBO_JX_LAYER              1065
#define IDC_COMBO_JX_AUTO_BONUS         1067
#define IDC_RADIO_JX_SINGLE             1069
#define IDC_RADIO_JX_RANDOM             1071
#define IDC_RADIO_JX_BEASKED            1073
#define IDC_RADIO_JX_ASK                1075
#define IDC_RUN_LOG                     1082
#define IDC_TANSUO_ROUND                1083
#define IDC_COMBO_TanSuo_LAYER          1085
#define IDC_COMBO_TanSuo_DIFF           1086
#define IDC_COMBO_TanSuo_MONSTER        1087
#define IDC_COMBO_TanSuo_AUTO_BONUS     1088
#define IDC_COMBO_YYH_LAYER             1102
#define IDC_RLZY_ROUND                  1103
#define IDC_COMBO_RLZY_LAYER            1104
#define IDC_RADIO_RLZY_SINGLE           1106
#define IDC_RADIO_RLZY_RANDOM           1107
#define IDC_RADIO_RLZY_BEASKED          1108
#define IDC_RADIO_RLZY_ASK              1109
#define IDC_VICTORY_RLZY                1110
#define IDC_COMBO_RLZY_PREFER_FRIEND    1112
#define IDC_TIPS9                       1114
#define IDC_ADOPT                       1115
#define IDC_RADIO_YH_SINGLE             1116
#define IDC_ADOPT2                      1116
#define IDC_RADIO_YH_RANDOM             1117
#define IDC_RADIO_YH_BEASKED            1118
#define IDC_RADIO_YH_ASK                1119
#define IDC_TIPS11                      1120
#define IDC_BTN_RLZY_ADDTOLIST          1121
#define IDC_TIPS12                      1121
#define IDC_BTN_EXPORT                  1122
#define IDC_TIPS13                      1122
#define IDC_COMBO_ADOPTKIND             1123
#define IDC_TIPS14                      1123
#define IDC_YL_ROUND                    1124
#define IDC_TIPS15                      1124
#define IDC_BTN_IMPORT                  1125
#define IDC_TIPS16                      1125
#define IDC_TRIPLE                      1126
#define IDC_COMBO_ADOPTSTAR             1127
#define IDC_COMBO_YL_MODE               1129
#define IDC_RADIO_YSZH_SINGLE           1130
#define IDC_RADIO_YSZH_BEASKED          1131
#define IDC_RADIO_YSZH_ASK              1132
#define IDC_RELATION                    1132
#define IDC_ROUND                       1133
#define IDC_AUTOREJECT                  1133
#define IDC_BTN_RECOVER                 1134
#define IDC_FLAG                        1134
#define IDC_BTN_YL_ADDTOLIST            1135
#define IDC_BOSSFLAG                    1135
#define IDC_LTORGT                      1136
#define IDC_COMBO_FL                    1136
#define IDC_COMBOTZ                     1136
#define IDC_COMBO_FL2                   1137
#define IDC_COMBO_TEAMERPOS             1137
#define IDC_CIRCLE                      1138
#define IDC_COMBO_FL3                   1138
#define IDC_WECHATPUSH                  1138
#define IDC_GRTP_ROUND                  1139
#define IDC_COMBO_FL4                   1139
#define IDC_BTN_TESTPUSH                1139
#define IDC_BTN_GRTP_ADDTOLIST          1140
#define IDC_FLAG2                       1140
#define IDC_NE_ROUND                    1141
#define IDC_PUBLIC                      1141
#define IDC_BTN_REST_ADDTOLIST          1142
#define IDC_REST_TIME                   1143
#define IDC_BTN_ADDTOLIST               1144
#define IDC_YSZH_ROUND                  1145
#define IDC_GROUP1                      1146
#define IDC_COMBO_YSZH_LAYER            1147
#define IDC_GROUP10                     1147
#define IDC_TEAM1                       1148
#define IDC_GROUP2                      1149
#define IDC_TEAM10                      1149
#define IDC_COMBO_AREA                  1150
#define IDC_GROUP11                     1150
#define IDC_BTN_HIDE                    1151
#define IDC_TEAM11                      1151
#define IDC_COMBO_YL_LAYER              1152
#define IDC_GROUP12                     1152
#define IDC_TEAM2                       1153
#define IDC_TEAM12                      1153
#define IDC_GROUP3                      1154
#define IDC_STATIC_IMG                  1154
#define IDC_TEAM13                      1155
#define IDC_STATIC_IMG2                 1155
#define IDC_TEAM3                       1156
#define IDC_GROUP13                     1156
#define IDC_STATIC_IMG3                 1156
#define IDC_TEAM14                      1157
#define IDC_STATIC_IMG4                 1157
#define IDC_GROUP4                      1158
#define IDC_STATIC_IMG5                 1158
#define IDC_COMBO_YSZH_PREFER_FRIEND    1159
#define IDC_TEAM15                      1159
#define IDC_STATIC_IMG6                 1159
#define IDC_TEAM4                       1160
#define IDC_GROUP14                     1160
#define IDC_BTN_YSZH_ADDTOLIST          1161
#define IDC_TEAM16                      1161
#define IDC_GROUP5                      1162
#define IDC_STARAREA                    1162
#define IDC_TEAM5                       1163
#define IDC_GROUP6                      1164
#define IDC_BAIGUI                      1165
#define IDC_TEAM6                       1166
#define IDC_GROUP7                      1167
#define IDC_REGION                      1168
#define IDC_TEAM7                       1169
#define IDC_PLOT                        1170
#define IDC_GROUP8                      1171
#define IDC_SMALLPVE                    1171
#define IDC_Active1                     1172
#define IDC_SMALLPVE2                   1172
#define IDC_LQ                          1172
#define IDC_PVP                         1173
#define IDC_TEAM8                       1174
#define IDC_READY                       1174
#define IDC_Active2                     1175
#define IDC_CLEAN                       1175
#define IDC_GROUP9                      1176
#define IDC_GETCARD                     1176
#define IDC_TEAM9                       1177
#define IDC_CHALLENGE                   1177
#define IDC_TEAM51                      1178
#define IDC_LIST_SHOW_ADDTASK           1200
#define IDC_BTN_START                   1203
#define IDC_BTN_STOP                    1204
#define IDC_BTN_SUSPEND                 1205
#define IDC_BTN_UPDATE                  1206
#define IDC_CHECK_JX_VICTORY            1209
#define IDC_TAB_RIGHT                   1212
#define IDC_COMBO_TanSuo_MODE           1215
#define IDC_COMBO_MAKINDS               1216
#define IDC_COMBO_JX_PREFER_FRIEND      1216
#define IDC_COMBO_PROGRESSBAR           1217
#define IDC_BTN_JX_ADDTOLIST            1218
#define IDC_COMBO_TanSuo_PREFER_FRIEND  1221
#define IDC_BTN_Tansuo_ADDTOLIST        1222
#define IDC_TIPS1                       1232
#define IDC_TIPS2                       1233
#define IDC_TIPS3                       1234
#define IDC_TIPS4                       1235
#define IDC_TIPS5                       1236
#define IDC_TIPS6                       1237
#define IDC_TPWAIT                      1300
#define IDC_YQFY_ROUND                  1500
#define IDC_COMBO_YQFY_KINDS            1502
#define IDC_COMBO_SUB                   1503
#define IDC_BTN_YQFY_ADDTOLIST          1504
#define IDC_YYH_ROUND                   1506
#define IDC_COMBO_RGMOUNT               1508
#define IDC_COMBO_PVPTYPE               1509
#define IDC_BTN_YYH_ADDTOLIST           1510
#define IDC_TIPS7                       2000
#define IDC_VERSION                     2001
#define IDC_SPEED                       2002
#define IDC_ISCHANGE                    2003
#define IDC_GETREWARD                   2003
#define IDC_CONDITION                   2004
#define IDC_MATERIAL                    2005
#define IDC_TASKUP                      2006
#define IDC_TASKDOWN                    2007
#define IDC_TUPOMODE                    2008
#define IDC_RADIO_HOT                   2009
#define IDC_AIEXPLORE                   2009
#define IDC_RADIO_COLLECT               2010
#define IDC_TIPS                        2011
#define IDC_TIPS8                       2012
#define IDC_EDIT_TOKEN                  2012
#define IDC_TIPSSUB                     2013
#define IDC_TIPS10                      2014
#define IDC_BTN_ADD                     2022

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1140
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
